<a href="https://colab.research.google.com/github/MaskeyRiddhi/AI-ML/blob/main/Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise on Functions:
Task - 1:

Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

In [ ]:
def convert_length(value, from_unit, to_unit):
    """
    Converts a given length value from one unit to another.

    Parameters:
    value (float): The value to be converted.
    from_unit (str): The unit of the original value (e.g., "m" for meter, "ft" for feet).
    to_unit (str): The unit to convert the value to (e.g., "ft" for feet, "m" for meter).

    Returns:
    float: The converted value in the target unit.
    """
    if from_unit == "m" and to_unit == "ft":
        return value * 3.28084
    elif from_unit == "ft" and to_unit == "m":
        return value / 3.28084
    else:
        raise ValueError("Unsupported length conversion.")

def convert_weight(value, from_unit, to_unit):
    """
    Converts a given weight value from one unit to another.

    Parameters:
    value (float): The value to be converted.
    from_unit (str): The unit of the original value (e.g., "kg" for kilograms, "lbs" for pounds).
    to_unit (str): The unit to convert the value to (e.g., "lbs" for pounds, "kg" for kilograms).

    Returns:
    float: The converted value in the target unit.
    """
    if from_unit == "kg" and to_unit == "lbs":
        return value * 2.20462
    elif from_unit == "lbs" and to_unit == "kg":
        return value / 2.20462
    else:
        raise ValueError("Unsupported weight conversion.")

def convert_volume(value, from_unit, to_unit):
    """
    Converts a given volume value from one unit to another.

    Parameters:
    value (float): The value to be converted.
    from_unit (str): The unit of the original value (e.g., "L" for liters, "gal" for gallons).
    to_unit (str): The unit to convert the value to (e.g., "gal" for gallons, "L" for liters).

    Returns:
    float: The converted value in the target unit.
    """
    if from_unit == "L" and to_unit == "gal":
        return value * 0.264172
    elif from_unit == "gal" and to_unit == "L":
        return value / 0.264172
    else:
        raise ValueError("Unsupported volume conversion.")

def main():
    """
    Main function that drives the unit conversion program.
    Prompts the user for the type of conversion, the value, and the units to convert.
    Handles errors gracefully and displays the result.
    """
    try:
        print("Welcome to the Unit Conversion Program!")
        print("Choose the type of conversion:")
        print("1. Length (meters to feet or feet to meters)")
        print("2. Weight (kilograms to pounds or pounds to kilograms)")
        print("3. Volume (liters to gallons or gallons to liters)")

        choice = input("Enter the number of your choice (1, 2, or 3): ").strip()

        if choice not in ["1", "2", "3"]:
            raise ValueError("Invalid choice! Please select a valid option (1, 2, or 3).")

        value = float(input("Enter the value to be converted: "))

        if choice == "1":
            print("For Length conversion, choose between meters (m) and feet (ft).")
            from_unit = input("Enter the unit to convert from (m/ft): ").strip().lower()
            to_unit = input("Enter the unit to convert to (m/ft): ").strip().lower()
            result = convert_length(value, from_unit, to_unit)

        elif choice == "2":
            print("For Weight conversion, choose between kilograms (kg) and pounds (lbs).")
            from_unit = input("Enter the unit to convert from (kg/lbs): ").strip().lower()
            to_unit = input("Enter the unit to convert to (kg/lbs): ").strip().lower()
            result = convert_weight(value, from_unit, to_unit)

        elif choice == "3":
            print("For Volume conversion, choose between liters (L) and gallons (gal).")
            from_unit = input("Enter the unit to convert from (L/gal): ").strip().lower()
            to_unit = input("Enter the unit to convert to (L/gal): ").strip().lower()
            result = convert_volume(value, from_unit, to_unit)

        print(f"{value} {from_unit.upper()} is equal to {result} {to_unit.upper()}.")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()


Welcome to the Unit Conversion Program!
Choose the type of conversion:
1. Length (meters to feet or feet to meters)
2. Weight (kilograms to pounds or pounds to kilograms)
3. Volume (liters to gallons or gallons to liters)
Enter the number of your choice (1, 2, or 3): 1
Enter the value to be converted: 5
For Length conversion, choose between meters (m) and feet (ft).
Enter the unit to convert from (m/ft): m
Enter the unit to convert to (m/ft): ft
5.0 M is equal to 16.4042 FT.


Task - 2:

Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

In [ ]:
def find_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numbers.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)

def find_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numbers.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    """
    Finds the maximum number in a list of numbers.

    Parameters:
    numbers (list): A list of numbers.

    Returns:
    float: The maximum number.
    """
    return max(numbers) if numbers else None

def find_minimum(numbers):
    """
    Finds the minimum number in a list of numbers.

    Parameters:
    numbers (list): A list of numbers.

    Returns:
    float: The minimum number.
    """
    return min(numbers) if numbers else None

def main():
    """
    Main function that drives the program.
    Prompts the user to select an operation and input a list of numbers.
    Handles errors gracefully and displays the result.
    """
    try:
        print("Welcome to the Mathematical Operations Program!")
        print("Choose an operation:")
        print("1. Find the sum")
        print("2. Find the average")
        print("3. Find the maximum")
        print("4. Find the minimum")

        choice = input("Enter the number of your choice (1, 2, 3, or 4): ").strip()

        if choice not in ["1", "2", "3", "4"]:
            raise ValueError("Invalid choice! Please select a valid option (1, 2, 3, or 4).")

        numbers_input = input("Enter the list of numbers (separated by spaces): ").strip()
        numbers = [float(num) for num in numbers_input.split()]

        if not numbers:
            raise ValueError("The list cannot be empty!")

        if choice == "1":
            result = find_sum(numbers)
            print(f"The sum of the numbers is: {result}")

        elif choice == "2":
            result = find_average(numbers)
            print(f"The average of the numbers is: {result}")

        elif choice == "3":
            result = find_maximum(numbers)
            print(f"The maximum number is: {result}")

        elif choice == "4":
            result = find_minimum(numbers)
            print(f"The minimum number is: {result}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()


Welcome to the Mathematical Operations Program!
Choose an operation:
1. Find the sum
2. Find the average
3. Find the maximum
4. Find the minimum
Enter the number of your choice (1, 2, 3, or 4): 3
Enter the list of numbers (separated by spaces): 9 6 10 15 0
The maximum number is: 15.0


# Exercise on List Manipulation:
1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

In [ ]:
def extract_every_other(lst):
    return lst[::2]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_every_other(input_list)
print("Output:", output_list)


Output: [1, 3, 5]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
output_list = get_sublist(input_list, start_index, end_index)
print("Output:", output_list)


Output: [3, 4, 5]


3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    return lst[::-1]

# Example usage:
input_list = [1, 2, 3, 4, 5]
output_list = reverse_list(input_list)
print("Reversed List:", output_list)


Reversed List: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [ ]:
def remove_first_last(lst):
    return lst[1:-1]

# Example usage:
input_list = [1, 2, 3, 4, 5]
output_list = remove_first_last(input_list)
print("Sublist without first and last elements:", output_list)


Sublist without first and last elements: [2, 3, 4]


5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.


In [ ]:
def get_first_n(lst, n):
    return lst[:n]

# Example usage:
input_list = [1, 2, 3, 4, 5]
n = 3
output_list = get_first_n(input_list, n)
print("First n elements:", output_list)


First n elements: [1, 2, 3]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.


In [ ]:
def get_last_n(lst, n):
    return lst[-n:]

# Example usage:
input_list = [1, 2, 3, 4, 5]
n = 2
output_list = get_last_n(input_list, n)
print("Last n elements:", output_list)


Last n elements: [4, 5]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.


In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)
print("Reversed and skipped elements:", output_list)


Reversed and skipped elements: [5, 3, 1]


# Exercise on Nested List:

1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.


In [ ]:
def flatten(lst):
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flat_list.extend(flatten(sublist))  # Recursively flatten nested lists
        else:
            flat_list.append(sublist)  # Add the element if it's not a list
    return flat_list

# Example usage:
nested_list = [[1, 2], [3, 4], [5]]
flattened_list = flatten(nested_list)
print("Flattened list:", flattened_list)


Flattened list: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

In [ ]:
def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]  # Move to the next level of the list using the current index
    return lst  # Return the element when all indices have been accessed

# Example usage:
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
element = access_nested_element(nested_list, indices)
print("Accessed element:", element)


Accessed element: 6


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).



In [ ]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, recursively call sum_nested
            total += sum_nested(item)
        else:  # If the item is a number, add it to the total
            total += item
    return total

# Example usage:
nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print("Sum of all elements:", result)


Sum of all elements: 21


4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.


In [ ]:
def remove_element(lst, elem):
    for i in range(len(lst)):
        if isinstance(lst[i], list):  # If the element is a sublist, recursively remove elem from it
            lst[i] = remove_element(lst[i], elem)
        else:
            # If the element is not a list, remove all occurrences of elem
            if lst[i] == elem:
                lst[i] = None  # Replace the element with None temporarily
    # Remove None values which are placeholders for removed elements
    lst = [x for x in lst if x is not None]
    return lst

# Example usage:
nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
result = remove_element(nested_list, element_to_remove)
print("Modified list:", result)


Modified list: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).


In [ ]:
def find_max(lst):
    max_elem = float('-inf')  # Initialize max_elem to negative infinity

    for item in lst:
        if isinstance(item, list):  # If the item is a list, recursively find the maximum in it
            max_elem = max(max_elem, find_max(item))
        else:
            max_elem = max(max_elem, item)  # Compare with the current item

    return max_elem

# Example usage:
nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print("Maximum element:", result)


Maximum element: 6


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.


In [ ]:
def count_occurrences(lst, elem):
    count = 0  # Initialize count to 0

    for item in lst:
        if isinstance(item, list):  # If the item is a list, recursively count occurrences
            count += count_occurrences(item, elem)
        else:
            if item == elem:  # If the item is equal to elem, increment the count
                count += 1

    return count

# Example usage:
nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)
print("Occurrences of", element_to_count, ":", result)


Occurrences of 2 : 3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.


In [ ]:
def deep_flatten(lst):
    flattened = []  # Initialize an empty list to hold the flattened elements

    for item in lst:
        if isinstance(item, list):  # If the item is a list, recursively flatten it
            flattened.extend(deep_flatten(item))
        else:
            flattened.append(item)  # If the item is not a list, append it directly

    return flattened

# Example usage:
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print("Flattened list:", result)


Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.


In [ ]:
def flatten(lst):
    flattened = []

    for item in lst:
        if isinstance(item, list):
            flattened.extend(flatten(item))  # Recursively flatten the sublist
        else:
            flattened.append(item)

    return flattened

def average_nested(lst):
    flattened_list = flatten(lst)  # Flatten the nested list
    if len(flattened_list) == 0:
        return 0  # Return 0 if the list is empty to avoid division by zero

    total_sum = sum(flattened_list)  # Sum all elements
    total_count = len(flattened_list)  # Count all elements
    return total_sum / total_count  # Return the average

# Example usage:
nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print("Average of all elements:", result)


Average of all elements: 3.5


# Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [1]:
import numpy as np

In [ ]:
# Initialize an empty array of size 2x2
empty_array = np.empty((2, 2))

print("Empty Array (2x2):")
print(empty_array)


Empty Array (2x2):
[[2.92518784e-316 0.00000000e+000]
 [5.31666808e-317 6.69917180e-310]]


2. Initialize an all one array with size 4X2.

In [ ]:
# Initialize an all-one array of size 4x2
ones_array = np.ones((4, 2))

print("All-One Array (4x2):")
print(ones_array)


All-One Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint:

In [ ]:
# Define shape, fill value, and data type
shape = (3, 3)  # Example shape
fill_value = 7  # Example fill value
dtype = np.int32  # Example data type

# Create the array
filled_array = np.full(shape, fill_value, dtype=dtype)

print("Filled Array:")
print(filled_array)


Filled Array:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.

In [ ]:
# Given array
original_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

# Create a new array of zeros with the same shape and type as original_array
zeros_array = np.zeros_like(original_array)

print("Original Array:")
print(original_array)

print("\nZeros Array:")
print(zeros_array)


Original Array:
[[1. 2. 3.]
 [4. 5. 6.]]

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]


5. Return a new array of ones with same shape and type as a given array.

In [ ]:
# Given array
original_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

# Create a new array of ones with the same shape and type as original_array
ones_array = np.ones_like(original_array)

print("Original Array:")
print(original_array)

print("\nOnes Array:")
print(ones_array)


Original Array:
[[1. 2. 3.]
 [4. 5. 6.]]

Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.

In [ ]:
# Given list
new_list = [1, 2, 3, 4]

# Convert list to NumPy array
array = np.array(new_list)

print("Original List:", new_list)
print("Converted NumPy Array:", array)


Original List: [1, 2, 3, 4]
Converted NumPy Array: [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

# Create an array with values from 10 to 49
arr = np.arange(10, 50)

print("Array with values from 10 to 49:")
print(arr)


Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.


In [ ]:
arr = np.arange(9)
matrix = arr.reshape(3,3)
print("3*3 Matrix with values from 0 to 8: ")
print (matrix)

3*3 Matrix with values from 0 to 8: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity_matrix = np.eye(3)
print("3*3 identity matrix")
print(identity_matrix)

3*3 identity matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.

In [ ]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array:",random_array)
print("Mean of the array:",mean_value)

Random Array: [0.24818943 0.03109591 0.36082494 0.90098186 0.148158   0.94127917
 0.29839725 0.64366796 0.0981488  0.61887338 0.36177267 0.56511619
 0.39771289 0.61563767 0.11810761 0.52603803 0.17691856 0.47713258
 0.94078543 0.86841471 0.68462669 0.7049064  0.96115179 0.91192061
 0.33953999 0.76707953 0.91179913 0.31365248 0.21156462 0.81731279]
Mean of the array: 0.532026901617166


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
random_array_10x10 = np.random.random((10,10))
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print("Random 10x10 Array:\n",random_array_10x10)
print("Minimum Value:",min_value)
print("Maximun Value:",max_value)

Random 10x10 Array:
 [[0.76779048 0.55490913 0.30648404 0.68935231 0.94691032 0.50497324
  0.06116253 0.44165268 0.34735261 0.2473848 ]
 [0.90807377 0.80822877 0.64128546 0.3868926  0.22340682 0.11213184
  0.8481585  0.87740769 0.02421939 0.91580053]
 [0.43374938 0.39220096 0.0098364  0.62564042 0.80863199 0.25332389
  0.2426336  0.57524842 0.33442891 0.3020543 ]
 [0.72253352 0.09995931 0.98186258 0.79427304 0.62926194 0.25464665
  0.0355338  0.38011077 0.86097624 0.49559072]
 [0.56081121 0.64788703 0.01780923 0.30755753 0.80429032 0.85024023
  0.20649507 0.62436762 0.84167398 0.64039411]
 [0.97891136 0.32638364 0.09707695 0.63713747 0.24829721 0.07214837
  0.76283559 0.08240846 0.66548635 0.58701466]
 [0.98396617 0.85694892 0.64778793 0.1299192  0.08737966 0.6445029
  0.37507836 0.63470487 0.64139584 0.10652989]
 [0.75376598 0.74494037 0.48208709 0.42339619 0.64317314 0.4707787
  0.34754368 0.4746907  0.28265631 0.51147002]
 [0.69683987 0.67144776 0.79227699 0.77994308 0.08125296 0.91

6. Create a zero array of size 10 and replace 5th element with 1.

In [2]:
# Create a zero array of size 10
zero_array = np.zeros(10)

# Replace the 5th element (index 4) with 1
zero_array[4] = 1

print("Modified Array:", zero_array)

Modified Array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [3]:
# Given array
arr = np.array([1, 2, 0, 0, 4, 0])

# Reverse the array
reversed_arr = arr[::-1]

print("Original Array:", arr)
print("Reversed Array:", reversed_arr)

Original Array: [1 2 0 0 4 0]
Reversed Array: [0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [4]:
# Define the size of the 2D array (e.g., 5x5)
rows, cols = 5, 5

# Create an array filled with zeros
array = np.zeros((rows, cols), dtype=int)

# Set the border elements to 1
array[0, :] = 1  # Top border
array[-1, :] = 1  # Bottom border
array[:, 0] = 1  # Left border
array[:, -1] = 1  # Right border

print("2D Array with 1 on border and 0 inside:\n", array)

2D Array with 1 on border and 0 inside:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [5]:
# Create an 8x8 array filled with zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill with 1s at alternate positions
checkerboard[1::2, ::2] = 1  # Odd rows, even columns
checkerboard[::2, 1::2] = 1  # Even rows, odd columns

print("8x8 Checkerboard Pattern:\n", checkerboard)

8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Problem - 3: Array Operations:
For the following arrays:

x = np.array([[1,2],[3,5]]) and

y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and

w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.

In [6]:
# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Add the arrays
result = np.add(x, y)  # or result = x + y

print("Sum of x and y:\n", result)

Sum of x and y:
 [[ 6  8]
 [10 13]]


2. Subtract the two array.

In [7]:
# Subtract the arrays
result = np.subtract(x, y)  # or result = x - y

print("Subtraction of y from x:\n", result)

Subtraction of y from x:
 [[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [8]:
# Define the array
x = np.array([[1, 2], [3, 5]])

# Multiply by an integer (e.g., 3)
result = np.multiply(x, 3)  # or result = x * 3

print("Array x multiplied by 3:\n", result)

Array x multiplied by 3:
 [[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.

In [9]:
# Define the array
x = np.array([[1, 2], [3, 5]])

# Square each element
squared_array = np.square(x)  # or squared_array = x ** 2

print("Squared Array:\n", squared_array)

Squared Array:
 [[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [10]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Dot product between v and w
dot_v_w = np.dot(v, w)

# Dot product between x and v
dot_x_v = np.dot(x, v)

# Dot product between x and y
dot_x_y = np.dot(x, y)

print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:\n", dot_x_v)
print("Dot product of x and y:\n", dot_x_y)

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [11]:
# Concatenate x and y along rows (axis=1)
concat_x_y = np.concatenate((x, y), axis=1)

# Concatenate v and w along columns (axis=0)
concat_v_w = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=0)

# Alternatively, you can also use vstack
# concat_v_w = np.vstack((v, w))

print("Concatenated x and y along rows:\n", concat_x_y)
print("Concatenated v and w along columns:\n", concat_v_w)

Concatenated x and y along rows:
 [[1 2 5 6]
 [3 5 7 8]]
Concatenated v and w along columns:
 [[ 9]
 [10]
 [11]
 [12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [12]:
x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

# Try to concatenate x and v
concat_x_v = np.concatenate((x, v), axis=0)

print("Concatenated x and v:\n", concat_x_v)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# Problem - 4: Matrix Operations:
• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.

In [13]:
# Given matrix A
A = np.array([[3, 4], [7, 8]])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A with A_inv to get the result
result = np.dot(A, A_inv)

# Print the result and the identity matrix
print("A * A_inv:\n", result)
print("Identity matrix I:\n", np.eye(2))

A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix I:
 [[1. 0.]
 [0. 1.]]


2. Prove AB ̸= BA.

In [14]:
import numpy as np

# Given matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Multiply A by B
AB = np.dot(A, B)

# Multiply B by A
BA = np.dot(B, A)

# Print the results of AB and BA
print("AB:\n", AB)
print("BA:\n", BA)


AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


3. Prove (AB)T = BTAT

In [15]:
# Given matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute (AB)^T
AB_T = np.transpose(np.dot(A, B))

# Compute B^T A^T
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))

# Print the results of both
print("Transpose of AB (AB)^T:\n", AB_T)
print("Product of Transpose of B and A (B^T A^T):\n", B_T_A_T)

Transpose of AB (AB)^T:
 [[23 51]
 [13 29]]
Product of Transpose of B and A (B^T A^T):
 [[23 51]
 [13 29]]


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [16]:
# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constant vector B
B = np.array([-1, -3, 9])

# Find the inverse of matrix A
A_inv = np.linalg.inv(A)

# Solve for X using the inverse of A
X = np.dot(A_inv, B)

# Print the solution
print("Solution (x, y, z):", X)

Solution (x, y, z): [ 2.  1. -2.]


# Experiment: How Fast is Numpy?

---




1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [17]:
import time
import numpy as np

# Creating two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000001, 2000001)]

# Element-wise addition using Python Lists
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()
python_list_time = end_time - start_time

# Creating two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)
array2 = np.arange(1000001, 2000001)

# Element-wise addition using NumPy Arrays
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
numpy_array_time = end_time - start_time

# Printing the time taken for both operations
print(f"Time taken for element-wise addition using Python Lists: {python_list_time:.6f} seconds")
print(f"Time taken for element-wise addition using NumPy Arrays: {numpy_array_time:.6f} seconds")


Time taken for element-wise addition using Python Lists: 0.117553 seconds
Time taken for element-wise addition using NumPy Arrays: 0.007588 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [18]:
# Element-wise multiplication using Python Lists
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()
python_list_time = end_time - start_time

# Creating two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)
array2 = np.arange(1000001, 2000001)

# Element-wise multiplication using NumPy Arrays
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
numpy_array_time = end_time - start_time

# Printing the time taken for both operations
print(f"Time taken for element-wise multiplication using Python Lists: {python_list_time:.6f} seconds")
print(f"Time taken for element-wise multiplication using NumPy Arrays: {numpy_array_time:.6f} seconds")

Time taken for element-wise multiplication using Python Lists: 0.122450 seconds
Time taken for element-wise multiplication using NumPy Arrays: 0.011249 seconds


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [19]:
# Dot product using Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()
python_list_time = end_time - start_time

# Creating two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)
array2 = np.arange(1000001, 2000001)

# Dot product using NumPy Arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
numpy_array_time = end_time - start_time

# Printing the time taken for both operations
print(f"Time taken for dot product using Python Lists: {python_list_time:.6f} seconds")
print(f"Time taken for dot product using NumPy Arrays: {numpy_array_time:.6f} seconds")

Time taken for dot product using Python Lists: 0.118026 seconds
Time taken for dot product using NumPy Arrays: 0.001626 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [20]:
# Create two 1000x1000 matrices using Python Lists
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i * j for j in range(1000)] for i in range(1000)]

# Start time for Python Lists matrix multiplication
start_time = time.time()

# Perform matrix multiplication manually
result_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]

# End time for Python Lists matrix multiplication
end_time = time.time()
python_list_time = end_time - start_time

# Matrix multiplication using NumPy Arrays

# Create two 1000x1000 matrices using NumPy
matrix1_np = np.random.rand(1000, 1000)
matrix2_np = np.random.rand(1000, 1000)

# Start time for NumPy matrix multiplication
start_time = time.time()

# Perform matrix multiplication using NumPy
result_np = np.dot(matrix1_np, matrix2_np)

# End time for NumPy matrix multiplication
end_time = time.time()
numpy_array_time = end_time - start_time

# Print the time taken for both operations
print(f"Time taken for matrix multiplication using Python Lists: {python_list_time:.6f} seconds")
print(f"Time taken for matrix multiplication using NumPy Arrays: {numpy_array_time:.6f} seconds")


Time taken for matrix multiplication using Python Lists: 214.454578 seconds
Time taken for matrix multiplication using NumPy Arrays: 0.084686 seconds
